# Generated by Django 4.1 on 2022-08-16 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firs_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('father_name', models.CharField(blank=True, max_length=30, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('account_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('adress', models.TextField(blank=True, null=True)),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(max_length=128)),
                ('price', models.TextField()),
                ('status', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=50)),
                ('vendor_code', models.IntegerField()),
                ('category', models.CharField(max_length=128)),
                ('amount_stack', models.IntegerField()),
                ('price', models.TextField()),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(upload_to='photos/<django.db.models.fields.CharField>')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('products', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('purchase_time', models.DateTimeField(auto_now_add=True)),
                ('price', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='musicforce.customer')),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='musicforce.delivery')),
                ('product', models.ManyToManyField(to='musicforce.product')),
            ],
        ),
        migrations.CreateModel(
            name='Supplie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('delivery_type', models.CharField(max_length=128)),
                ('complited', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='musicforce.product')),
                ('saller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='musicforce.seller')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='saller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='musicforce.seller'),
        ),
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='musicforce.customer')),
                ('product', models.ManyToManyField(to='musicforce.product')),
            ],
        ),
    ]
