# Generated by Django 4.1 on 2022-08-17 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicforce', '0002_alter_delivery_price_alter_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='account_name',
        ),
    ]
